Parameters:
  TableName:
    Type: String
    Default: MicrobItems
    Description: The name of the dynamodb table
  PartitionKey:
    Type: String
    Default: Id
    Description: The name of the main parition key
#  SortKey:
#    Type: String
#    Default: PublishDate
#    Description: The name of the primary sort key
  SecondaryIndex:
    Type: String
    Default: Title
    Description: The name of the secondary index
  ReadCapacityUnits:
    Default: 5
    Description: Dynamo read capacity units
    Type: Number
  WriteCapacityUnits:
    Default: 5
    Description: Dynamo write capacity units
    Type: Number

  CorsTableName:
    Type: String
    Default: CorsOrigins
    Description: The name of the CORS dynamodb table
  CorsPartitionKey:
    Type: String
    Default: Origin
    Description: The name of the main parition key for the CORS table

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName

      AttributeDefinitions:
      - AttributeName:
          Ref: PartitionKey
        AttributeType: S
#      - AttributeName:
#          Ref: SortKey
#        AttributeType: S
      - AttributeName:
          Ref: SecondaryIndex
        AttributeType: S

      KeySchema:
      - AttributeName:
          Ref: PartitionKey
        KeyType: HASH
#      - AttributeName:
#          Ref: SortKey
#        KeyType: RANGE

      GlobalSecondaryIndexes:
      - IndexName:
          Ref: SecondaryIndex
        KeySchema:
        - AttributeName:
            Ref: SecondaryIndex
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits

#      TimeToLiveSpecification:
#        AttributeName: ExpirationTime
#        Enabled: true

  CorsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: CorsTableName

      AttributeDefinitions:
      - AttributeName:
          Ref: CorsPartitionKey
        AttributeType: S

      KeySchema:
      - AttributeName:
          Ref: CorsPartitionKey
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits

Outputs:
  EventsJsonArchive:
    Value:
      Ref: DynamoDBTable

